"""
Django settings for stratasec project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import datetime
from pathlib import Path
import os
import socket
from django.contrib.messages import constants as messages
from pathlib import Path
import os, json
from dotenv import dotenv_values
from cryptography.hazmat.primitives import serialization


def _smart_cast(value: str):
    s = value.strip()

    # boolean
    if s.lower() in ("true", "1", "yes", "on"):
        return True
    if s.lower() in ("false", "0", "no", "off"):
        return False

    # int
    try:
        return int(s)
    except ValueError:
        pass

    # float
    try:
        return float(s)
    except ValueError:
        pass

    # lista simples por vírgula (se não for JSON explícito)
    if "," in s and not (s.startswith("{") or s.startswith("[")):
        return [item.strip() for item in s.split(",")]

    # JSON (dict/list/null/true/false/num/str)
    try:
        return json.loads(s)
    except Exception:
        return s  # string pura


START_TIME = datetime.datetime.now()
APP_STARTED = str(int(datetime.datetime.now().timestamp()))
VERSION = 'v0.1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR
if not DEBUG:
    DATA_DIR = "/app/data"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pk+@s=gxiu_v_z!a@8(b0d6l!j28amk_@)jg54f8le^ma99pfy'

ALLOWED_HOSTS = ['*']

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
USE_I18N = True
USE_TZ = True
LANGUAGE_CODE = 'en-US'
TIME_ZONE = 'America/Sao_Paulo'

RSA_PUB_KEY = ""

# 1) Carrega o .env
_env = dotenv_values(DATA_DIR / ".env")  # não polui os.environ

# 2) Promove apenas variáveis MAIÚSCULAS do .env que ainda não existem no módulo
for key, val in (_env or {}).items():
    if not key or not key.isupper():
        continue
    #if key in globals():  # já definido acima? respeita o já definido
    #    continue
    if key == "RSA_PASSPHRASE":
        continue
    if key in os.environ:
        continue  # SO manda mais que o .env
    globals()[key] = _smart_cast(val)

# Load Public key
try:
    PUBLIC_KEY = serialization.load_pem_public_key(
        f"-----BEGIN PUBLIC KEY-----\n{RSA_PUB_KEY}\n-----END PUBLIC KEY-----".encode("UTF-8")
        )
except Exception as e:
    print("Error loading RSA public KEY")
    if os.path.isfile(BASE_DIR / ".env"):
        raise e

# Automatically add the current machine's local IP address to ALLOWED_HOSTS
try:
    hostname = socket.gethostname()
    local_ip = socket.gethostbyname(hostname)
    if local_ip not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(local_ip)
except Exception:
    pass

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'rest_framework',
    'corsheaders',
    'django_filters',

    'raspsec'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stratasec.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stratasec.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(DATA_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'raspsec.User'


USE_THOUSAND_SEPARATOR = True

SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_SECONDS = 60 * 60  # 60 minutos
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  # Usado para dev
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # usado em produção

if DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'raspsec', 'static')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher'
]

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',  # <-- troca 'error' por 'danger'
}

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

CRONJOBS = [
    ('* * * * *', 'raspsec.cron.watchdog'),
]

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'raspsec.jwe_auth.JWEAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'raspsec.permissions.DenyPasswordChangeToken',
    ],
}

# JWE Token settings
JWE_TOKEN_LIFETIME = 20 * 60  # 20 minutes

# CORS
CORS_ALLOW_CREDENTIALS = True
_cors_origins = os.environ.get('CORS_ORIGINS', 'http://localhost:3000')
if _cors_origins.strip() == '*':
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]

# Email / SMTP
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@raspsec.local')

CRONJOBS = [
    # em ambiente de teste manter 0 5 * * *
    # em produção mudar para * * * * *
    ('* * * * *', 'raspsec.cron.watchdog'),
]
